// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj4zuBHB3C1YxoLgFN21SHoV5TwXnx9EA',
    appId: '1:1030322629915:web:d911bccf1223c827a737be',
    messagingSenderId: '1030322629915',
    projectId: 'expensestracker-54ed7',
    authDomain: 'expensestracker-54ed7.firebaseapp.com',
    storageBucket: 'expensestracker-54ed7.appspot.com',
    measurementId: 'G-VS6CKBZWCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClzZf8_A3nO63LRcFz2BwSoMqy6pcFHms',
    appId: '1:1030322629915:android:8e4453fcc5ec5b5ea737be',
    messagingSenderId: '1030322629915',
    projectId: 'expensestracker-54ed7',
    storageBucket: 'expensestracker-54ed7.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj4zuBHB3C1YxoLgFN21SHoV5TwXnx9EA',
    appId: '1:1030322629915:web:83711077ee08800ba737be',
    messagingSenderId: '1030322629915',
    projectId: 'expensestracker-54ed7',
    authDomain: 'expensestracker-54ed7.firebaseapp.com',
    storageBucket: 'expensestracker-54ed7.appspot.com',
    measurementId: 'G-MZSFVTTRSK',
  );
}
